# Generated by Django 5.2 on 2025-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_scinet", "0002_interaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="type",
            field=models.CharField(
                choices=[("like", "Lajk"), ("comment", "Komentarz")], max_length=10
            ),
        ),
    ]
