# Generated by Django 5.2 on 2025-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scinet', '0006_article_created_at_article_file_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/articles/images/'),
        ),
    ]
